# Generated by Django 3.1.5 on 2021-01-29 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
