# Generated by Django 3.1.5 on 2021-02-09 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pubgUsername',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
