# Generated by Django 3.1.5 on 2021-02-15 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userlogin', '0004_profile_pubgusername'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matchId', models.IntegerField()),
                ('kills', models.IntegerField()),
                ('deaths', models.IntegerField()),
                ('damage', models.IntegerField()),
                ('dbno', models.IntegerField()),
                ('revives', models.IntegerField()),
                ('timeAlive', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userlogin.profile')),
            ],
        ),
    ]
