# Generated by Django 3.1.5 on 2021-02-15 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stats',
            name='deaths',
        ),
        migrations.AddField(
            model_name='stats',
            name='deathType',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
