# Generated by Django 3.1.5 on 2021-02-15 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_auto_20210215_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='matchId',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
